### ISSUE TITLE
Auto Save Apps

### ISSUE THREAD

**Issue by SManAT** [valueerrorx/life-exam#54]
in list
'calligrawords', 'calligrasheets', 'words', 'sheets', 'writer', 'kate', 'unbenannt', 'geogebra', 'calc', 'spreadsheets', 'wxmaxima'

something missing?

**Comment by valueerrorx** [comment]
gute frage..  sieht gut aus fürs erste... kann man ja recht einfach erweitern ;-)

**Comment by SManAT** [comment]
jup, dachte mir das Issue dient als Merkzettel ;)

**Comment by SManAT** [comment]
done
